version: "3"

services:
  ControllerOne:
    image: flowctrltest
    volumes:
      - /Users/liam/Documents/dev/thirdYear/csu33031-ComputerNetworks/FlowControl/src:/code
    command: java -cp /code Controller 1
  ControllerTwo:
    image: flowctrltest
    volumes:
      - /Users/liam/Documents/dev/thirdYear/csu33031-ComputerNetworks/FlowControl/src:/code
    command: java -cp /code Controller 2
  ControllerThree:
    image: flowctrltest
    volumes:
      - /Users/liam/Documents/dev/thirdYear/csu33031-ComputerNetworks/FlowControl/src:/code
    command: java -cp /code Controller 3

  application:
    image: flowctrltest
    volumes:
      - /Users/liam/Documents/dev/thirdYear/csu33031-ComputerNetworks/FlowControl/src:/code
    command: java -cp /code Application

  forwardingService:
    image: flowctrltest
    volumes:
      - /Users/liam/Documents/dev/thirdYear/csu33031-ComputerNetworks/FlowControl/src:/code
    command: java -cp /code ForwardingService

  # wireshark:
  #   image: wiresharkcontainer
  #   command: wireshark --display host.docker.internal:0